import { build } from 'esbuild';
import { mkdir, readFile, writeFile, copyFile } from 'node:fs/promises';

const worker = await build({
  entryPoints: ['src/mp3/worker.ts'], bundle: true, write: false, format: 'iife',
  platform: 'browser', target: 'es2022', minify: true, legalComments: 'inline',
});
await writeFile('dist/mp3-worker-source.js', `// Generated by scripts/build-mp3.mjs.\nexport const mp3WorkerSource = ${JSON.stringify(worker.outputFiles[0].text)};\n`);
// A regular script for existing HTML apps; no package manager or runtime downloads needed.
await mkdir('dist/standalone', { recursive: true });
await build({
  entryPoints: ['dist/mp3.js'], bundle: true, outfile: 'dist/standalone/browser-mp3.js',
  format: 'iife', globalName: 'BrowserMp3', platform: 'browser', target: 'es2022', minify: true,
  banner: { js: '/*! Browser MP3: MIT wrapper; includes unmodified @breezystack/lamejs 1.2.7 (LGPL-3.0). See THIRD_PARTY_NOTICES.md. */' },
});
await Promise.all([
  copyFile('LICENSE.md', 'dist/standalone/LICENSE.md'),
  copyFile('THIRD_PARTY_NOTICES.md', 'dist/standalone/THIRD_PARTY_NOTICES.md'),
  copyFile('node_modules/@breezystack/lamejs/LICENSE', 'dist/standalone/LAME-NOTICE.txt'),
  copyFile('examples/mp3-export/index.html', 'dist/standalone/index.html'),
]);
const size = (await readFile('dist/standalone/browser-mp3.js')).byteLength;
console.log(`Standalone MP3 module: ${size} bytes (encoder and worker included).`);
